// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type Account struct {
	AccountName string          `json:"account_name"`
	Groups      json.RawMessage `json:"groups"`
	Id          int             `json:"id"`
}

type AccountClientDomain struct {
	Accounts json.RawMessage `json:"accounts"`
}

type AiSearchVolume struct {
	History           json.RawMessage `json:"history"`
	Id                int             `json:"id"`
	SearchVolume      int             `json:"search_volume"`
	SearchVolumeTotal int             `json:"search_volume_total"`
}

type AiSearchVolumeHistory struct {
	Date              string `json:"date"`
	SearchVolume      int    `json:"search_volume"`
	SearchVolumeTotal int    `json:"search_volume_total"`
}

type ApiFilter struct {
	Filters json.RawMessage `json:"filters"`
	Id      int             `json:"id"`
	Name    string          `json:"name"`
}

type BrandSchemaOut struct {
	BrandList            string `json:"brand_list"`
	DefaultCountrylocale string `json:"default_countrylocale"`
	DisplayName          string `json:"display_name"`
	Domain               string `json:"domain"`
	ExactMatch           string `json:"exact_match"`
	GroupId              string `json:"group_id"`
	Id                   int    `json:"id"`
}

type BrandSchemaUpdateValidated struct {
	BrandList            string `json:"brand_list"`
	DefaultCountrylocale string `json:"default_countrylocale"`
	DisplayName          string `json:"display_name"`
	Domain               string `json:"domain"`
	ExactMatch           string `json:"exact_match"`
	GroupId              string `json:"group_id"`
}

type BrandSchemaValidated struct {
	BrandList            json.RawMessage `json:"brand_list"`
	DefaultCountrylocale string          `json:"default_countrylocale"`
	DisplayName          string          `json:"display_name"`
	Domain               string          `json:"domain"`
	ExactMatch           bool            `json:"exact_match"`
	GroupId              int             `json:"group_id"`
}

type Client struct {
	Account   json.RawMessage `json:"account"`
	CreatedAt string          `json:"created_at"`
	Id        int             `json:"id"`
	Name      string          `json:"name"`
}

type Competitor struct {
	CreatedAt              string          `json:"created_at"`
	DisplayName            string          `json:"display_name"`
	Domain                 string          `json:"domain"`
	FacebookProfile        string          `json:"facebook_profile"`
	GoogleBusinessName     string          `json:"google_business_name"`
	GoogleBusinessNameList json.RawMessage `json:"google_business_name_list"`
	History                json.RawMessage `json:"history"`
	Id                     int             `json:"id"`
	InstagramProfile       string          `json:"instagram_profile"`
	LinkedinProfile        string          `json:"linkedin_profile"`
	TiktokProfile          string          `json:"tiktok_profile"`
	XHandle                string          `json:"x_handle"`
}

type CompetitorHistory struct {
	AboveTheFold                int             `json:"above_the_fold"`
	AiSearchVolume              int             `json:"ai_search_volume"`
	AiShareOfVoice              int             `json:"ai_share_of_voice"`
	AiTrafficValue              int             `json:"ai_traffic_value"`
	AverageCtr                  float64         `json:"average_ctr"`
	AverageCtrMax               float64         `json:"average_ctr_max"`
	AverageLocalPackRank        float64         `json:"average_local_pack_rank"`
	AverageRank                 float64         `json:"average_rank"`
	AvgBaseRank                 float64         `json:"avg_base_rank"`
	CommercialIntent            int             `json:"commercial_intent"`
	Date                        string          `json:"date"`
	EstimatedVisits             int             `json:"estimated_visits"`
	InformationalIntent         int             `json:"informational_intent"`
	KeywordsWithAiOverview      int             `json:"keywords_with_ai_overview"`
	KeywordsWithAiOverviewOwned int             `json:"keywords_with_ai_overview_owned"`
	NavigationalIntent          int             `json:"navigational_intent"`
	PixelsFromTop               float64         `json:"pixels_from_top"`
	RankingDistribution         json.RawMessage `json:"ranking_distribution"`
	RankingMovement             json.RawMessage `json:"ranking_movement"`
	SearchVolume                int             `json:"search_volume"`
	ShareOfVoice                int             `json:"share_of_voice"`
	ShareOfVoicePercentage      float64         `json:"share_of_voice_percentage"`
	TrafficValue                int             `json:"traffic_value"`
	TransactionalIntent         int             `json:"transactional_intent"`
}

type CompetitorLLM struct {
	BrandList   json.RawMessage `json:"brand_list"`
	CreatedAt   string          `json:"created_at"`
	DisplayName string          `json:"display_name"`
	Domain      string          `json:"domain"`
	Id          int             `json:"id"`
	Pinned      bool            `json:"pinned"`
}

type CountryLocale struct {
	CountryCode string `json:"country_code"`
	Id          int    `json:"id"`
	Locale      string `json:"locale"`
	LocaleShort string `json:"locale_short"`
	Region      string `json:"region"`
}

type CountryLocaleSchema struct {
	CountryCode string `json:"country_code"`
	Id          int    `json:"id"`
	LocaleShort string `json:"locale_short"`
}

type DefaultSearchSettingSearchEngine struct {
	SearchEngine    string          `json:"search_engine"`
	SearchTypeNames json.RawMessage `json:"search_type_names"`
}

type DefaultSearchSettings struct {
	Countrylocale         string          `json:"countrylocale"`
	EnableAutocorrect     bool            `json:"enable_autocorrect"`
	IgnoreFeaturedSnippet bool            `json:"ignore_featured_snippet"`
	IgnoreLocalResults    bool            `json:"ignore_local_results"`
	Locations             json.RawMessage `json:"locations"`
	Primary               bool            `json:"primary"`
	SearchEngineNames     json.RawMessage `json:"search_engine_names"`
}

type DeleteKeywordInput struct {
	KeywordIds json.RawMessage `json:"keyword_ids"`
}

type DeletePromptInput struct {
	PromptIds json.RawMessage `json:"prompt_ids"`
}

type Domain struct {
	Competitors            json.RawMessage `json:"competitors"`
	CreatedAt              string          `json:"created_at"`
	DisplayName            string          `json:"display_name"`
	Domain                 string          `json:"domain"`
	FacebookProfile        string          `json:"facebook_profile"`
	GoogleBusinessName     string          `json:"google_business_name"`
	GoogleBusinessNameList json.RawMessage `json:"google_business_name_list"`
	Group                  json.RawMessage `json:"group"`
	History                json.RawMessage `json:"history"`
	Id                     int             `json:"id"`
	InstagramProfile       string          `json:"instagram_profile"`
	LastScraped            string          `json:"last_scraped"`
	LinkedinProfile        string          `json:"linkedin_profile"`
	TiktokProfile          string          `json:"tiktok_profile"`
	XHandle                string          `json:"x_handle"`
}

type DomainGet struct {
	DisplayName string `json:"display_name"`
	Domain      string `json:"domain"`
	Id          int    `json:"id"`
}

type DomainHistory struct {
	AboveTheFold                int             `json:"above_the_fold"`
	AiSearchVolume              int             `json:"ai_search_volume"`
	AiShareOfVoice              int             `json:"ai_share_of_voice"`
	AiTrafficValue              int             `json:"ai_traffic_value"`
	AverageCtr                  float64         `json:"average_ctr"`
	AverageCtrMax               float64         `json:"average_ctr_max"`
	AverageLocalPackRank        float64         `json:"average_local_pack_rank"`
	AverageRank                 float64         `json:"average_rank"`
	AvgBaseRank                 float64         `json:"avg_base_rank"`
	CommercialIntent            int             `json:"commercial_intent"`
	Date                        string          `json:"date"`
	EstimatedVisits             int             `json:"estimated_visits"`
	InformationalIntent         int             `json:"informational_intent"`
	KeywordsWithAiOverview      int             `json:"keywords_with_ai_overview"`
	KeywordsWithAiOverviewOwned int             `json:"keywords_with_ai_overview_owned"`
	NavigationalIntent          int             `json:"navigational_intent"`
	PixelsFromTop               float64         `json:"pixels_from_top"`
	RankingDistribution         json.RawMessage `json:"ranking_distribution"`
	RankingMovement             json.RawMessage `json:"ranking_movement"`
	SearchVolume                int             `json:"search_volume"`
	ShareOfVoice                int             `json:"share_of_voice"`
	ShareOfVoicePercentage      float64         `json:"share_of_voice_percentage"`
	TrafficValue                int             `json:"traffic_value"`
	TransactionalIntent         int             `json:"transactional_intent"`
}

type DomainLLM struct {
	BrandList   json.RawMessage `json:"brand_list"`
	Competitors json.RawMessage `json:"competitors"`
	CreatedAt   string          `json:"created_at"`
	DisplayName string          `json:"display_name"`
	Domain      string          `json:"domain"`
	Group       json.RawMessage `json:"group"`
	History     json.RawMessage `json:"history"`
	Id          int             `json:"id"`
	LastScraped string          `json:"last_scraped"`
}

type DomainLLMHistory struct {
	AverageRank              float64         `json:"average_rank"`
	AverageSentiment         float64         `json:"average_sentiment"`
	AverageTopProximityScore float64         `json:"average_top_proximity_score"`
	AverageVisibility        float64         `json:"average_visibility"`
	AverageWebSearchRate     float64         `json:"average_web_search_rate"`
	BrandMentions            int             `json:"brand_mentions"`
	Date                     string          `json:"date"`
	RankingDistribution      json.RawMessage `json:"ranking_distribution"`
	VisibilityMovement       json.RawMessage `json:"visibility_movement"`
}

type DomainSchemaOut struct {
	DefaultSearchsettingsNames string `json:"default_searchsettings_names"`
	DisplayName                string `json:"display_name"`
	Domain                     string `json:"domain"`
	ExactMatch                 string `json:"exact_match"`
	FacebookProfile            string `json:"facebook_profile"`
	GoogleBusinessNameList     string `json:"google_business_name_list"`
	GroupId                    string `json:"group_id"`
	Id                         int    `json:"id"`
	IncludeSubdomains          string `json:"include_subdomains"`
	InstagramProfile           string `json:"instagram_profile"`
	LinkedinProfile            string `json:"linkedin_profile"`
	ShareOfVoicePercentage     string `json:"share_of_voice_percentage"`
	TiktokProfile              string `json:"tiktok_profile"`
	XHandle                    string `json:"x_handle"`
}

type DomainSchemaUpdateValidated struct {
	DefaultSearchsettingsNames string `json:"default_searchsettings_names"`
	DisplayName                string `json:"display_name"`
	Domain                     string `json:"domain"`
	ExactMatch                 string `json:"exact_match"`
	FacebookProfile            string `json:"facebook_profile"`
	GoogleBusinessNameList     string `json:"google_business_name_list"`
	GroupId                    string `json:"group_id"`
	IncludeSubdomains          string `json:"include_subdomains"`
	InstagramProfile           string `json:"instagram_profile"`
	LinkedinProfile            string `json:"linkedin_profile"`
	ShareOfVoicePercentage     string `json:"share_of_voice_percentage"`
	TiktokProfile              string `json:"tiktok_profile"`
	XHandle                    string `json:"x_handle"`
}

type DomainSchemaValidated struct {
	DefaultSearchsettingsNames json.RawMessage `json:"default_searchsettings_names"`
	DisplayName                string          `json:"display_name"`
	Domain                     string          `json:"domain"`
	ExactMatch                 bool            `json:"exact_match"`
	FacebookProfile            string          `json:"facebook_profile"`
	GoogleBusinessNameList     string          `json:"google_business_name_list"`
	GroupId                    int             `json:"group_id"`
	IncludeSubdomains          bool            `json:"include_subdomains"`
	InstagramProfile           string          `json:"instagram_profile"`
	LinkedinProfile            string          `json:"linkedin_profile"`
	ShareOfVoicePercentage     bool            `json:"share_of_voice_percentage"`
	TiktokProfile              string          `json:"tiktok_profile"`
	XHandle                    string          `json:"x_handle"`
}

type FullSerp struct {
	CreatedAt    string          `json:"created_at"`
	Elements     json.RawMessage `json:"elements"`
	SearchIntent json.RawMessage `json:"search_intent"`
	TopDomain    string          `json:"top_domain"`
}

type Group struct {
	AccountId int    `json:"account_id"`
	Name      string `json:"name"`
}

type GroupGet struct {
	Domains   json.RawMessage `json:"domains"`
	GroupName string          `json:"group_name"`
	Id        int             `json:"id"`
}

type GroupOut struct {
	AccountId int    `json:"account_id"`
	Id        int    `json:"id"`
	Name      string `json:"name"`
}

type GroupUpdate struct {
	AccountId string `json:"account_id"`
	Name      string `json:"name"`
}

type GroupUpdateOut struct {
	AccountId string `json:"account_id"`
	Id        int    `json:"id"`
	Name      string `json:"name"`
}

type Keyword struct {
	AiSearchVolume       json.RawMessage `json:"ai_search_volume"`
	CompetitorRanks      json.RawMessage `json:"competitor_ranks"`
	CreatedAt            string          `json:"created_at"`
	Description          string          `json:"description"`
	DynamicTags          json.RawMessage `json:"dynamic_tags"`
	Folders              json.RawMessage `json:"folders"`
	FullSerp             json.RawMessage `json:"full_serp"`
	Id                   int             `json:"id"`
	InitialRank          json.RawMessage `json:"initial_rank"`
	Keyword              string          `json:"keyword"`
	PeopleAlsoAsk        json.RawMessage `json:"people_also_ask"`
	PeopleAlsoSearchFor  json.RawMessage `json:"people_also_search_for"`
	PreferredLandingPage json.RawMessage `json:"preferred_landing_page"`
	Ranks                json.RawMessage `json:"ranks"`
	RelatedQuestions     json.RawMessage `json:"related_questions"`
	RelatedSearches      json.RawMessage `json:"related_searches"`
	SearchEngine         json.RawMessage `json:"search_engine"`
	SearchLocale         json.RawMessage `json:"search_locale"`
	SearchLocation       string          `json:"search_location"`
	SearchType           int             `json:"search_type"`
	SearchVolume         json.RawMessage `json:"search_volume"`
	SearchVolumeLocal    json.RawMessage `json:"search_volume_local"`
	Starred              bool            `json:"starred"`
	Tags                 json.RawMessage `json:"tags"`
}

type KeywordCompetitorRank struct {
	AiShareOfVoice         int             `json:"ai_share_of_voice"`
	Competitor             json.RawMessage `json:"competitor"`
	CreatedAt              string          `json:"created_at"`
	Ctr                    float64         `json:"ctr"`
	CtrMax                 float64         `json:"ctr_max"`
	EstimatedVisits        int             `json:"estimated_visits"`
	HighestRankingPage     string          `json:"highest_ranking_page"`
	Id                     int             `json:"id"`
	Rank                   int             `json:"rank"`
	ShareOfVoice           int             `json:"share_of_voice"`
	ShareOfVoicePercentage float64         `json:"share_of_voice_percentage"`
}

type KeywordIn struct {
	Description           string          `json:"description"`
	DomainId              int             `json:"domain_id"`
	EnableAutocorrect     bool            `json:"enable_autocorrect"`
	IgnoreFeaturedSnippet bool            `json:"ignore_featured_snippet"`
	IgnoreInShareOfVoice  bool            `json:"ignore_in_share_of_voice"`
	IgnoreLocalResults    bool            `json:"ignore_local_results"`
	Keywords              json.RawMessage `json:"keywords"`
	Searchsettings        json.RawMessage `json:"searchsettings"`
	Starred               bool            `json:"starred"`
	Tags                  json.RawMessage `json:"tags"`
}

type KeywordInitialRank struct {
	AboveTheFold           bool            `json:"above_the_fold"`
	AiOverviewText         string          `json:"ai_overview_text"`
	AiOverviewUrls         json.RawMessage `json:"ai_overview_urls"`
	AiShareOfVoice         int             `json:"ai_share_of_voice"`
	AiTrafficValue         float64         `json:"ai_traffic_value"`
	BaseRank               int             `json:"base_rank"`
	BrowserPositionX1      int             `json:"browser_position_x1"`
	BrowserPositionX2      int             `json:"browser_position_x2"`
	BrowserPositionY1      int             `json:"browser_position_y1"`
	BrowserPositionY2      int             `json:"browser_position_y2"`
	CountAiOverviewUrls    int             `json:"count_ai_overview_urls"`
	CreatedAt              string          `json:"created_at"`
	Ctr                    float64         `json:"ctr"`
	CtrMax                 float64         `json:"ctr_max"`
	EstimatedVisits        int             `json:"estimated_visits"`
	ExtraRanks             json.RawMessage `json:"extra_ranks"`
	HighestRankingPage     string          `json:"highest_ranking_page"`
	Id                     int             `json:"id"`
	LandingPage            json.RawMessage `json:"landing_page"`
	LocalPackRank          int             `json:"local_pack_rank"`
	MaxAiSov               int             `json:"max_ai_sov"`
	MaxAiTrafficValue      float64         `json:"max_ai_traffic_value"`
	MaxRank                int             `json:"max_rank"`
	MaxSov                 int             `json:"max_sov"`
	MaxSovPercentage       float64         `json:"max_sov_percentage"`
	PageSerpFeatures       json.RawMessage `json:"page_serp_features"`
	Rank                   int             `json:"rank"`
	SearchIntent           json.RawMessage `json:"search_intent"`
	ShareOfVoice           int             `json:"share_of_voice"`
	ShareOfVoicePercentage float64         `json:"share_of_voice_percentage"`
	TitleDescription       json.RawMessage `json:"title_description"`
	TopDomain              string          `json:"top_domain"`
}

type KeywordOut struct {
	Country       string `json:"country"`
	Countrylocale string `json:"countrylocale"`
	Id            string `json:"id"`
	Keyword       string `json:"keyword"`
	Language      string `json:"language"`
	Location      string `json:"location"`
	SearchEngine  string `json:"search_engine"`
	SearchType    string `json:"search_type"`
}

type KeywordRank struct {
	AboveTheFold           bool            `json:"above_the_fold"`
	AiOverviewText         string          `json:"ai_overview_text"`
	AiOverviewUrls         json.RawMessage `json:"ai_overview_urls"`
	AiShareOfVoice         int             `json:"ai_share_of_voice"`
	AiTrafficValue         float64         `json:"ai_traffic_value"`
	BaseRank               int             `json:"base_rank"`
	BrowserPositionX1      int             `json:"browser_position_x1"`
	BrowserPositionX2      int             `json:"browser_position_x2"`
	BrowserPositionY1      int             `json:"browser_position_y1"`
	BrowserPositionY2      int             `json:"browser_position_y2"`
	CountAiOverviewUrls    int             `json:"count_ai_overview_urls"`
	CreatedAt              string          `json:"created_at"`
	Ctr                    float64         `json:"ctr"`
	CtrMax                 float64         `json:"ctr_max"`
	EstimatedVisits        int             `json:"estimated_visits"`
	ExtraRanks             json.RawMessage `json:"extra_ranks"`
	HighestRankingPage     string          `json:"highest_ranking_page"`
	Id                     int             `json:"id"`
	LandingPage            json.RawMessage `json:"landing_page"`
	LocalPackRank          int             `json:"local_pack_rank"`
	MaxAiSov               int             `json:"max_ai_sov"`
	MaxAiTrafficValue      float64         `json:"max_ai_traffic_value"`
	MaxRank                int             `json:"max_rank"`
	MaxSov                 int             `json:"max_sov"`
	MaxSovPercentage       float64         `json:"max_sov_percentage"`
	PageSerpFeatures       json.RawMessage `json:"page_serp_features"`
	Rank                   int             `json:"rank"`
	SearchIntent           json.RawMessage `json:"search_intent"`
	ShareOfVoice           int             `json:"share_of_voice"`
	ShareOfVoicePercentage float64         `json:"share_of_voice_percentage"`
	TitleDescription       json.RawMessage `json:"title_description"`
	TopDomain              string          `json:"top_domain"`
}

type KeywordSettings struct {
	Description           string `json:"description"`
	DomainId              string `json:"domain_id"`
	EnableAutocorrect     string `json:"enable_autocorrect"`
	IgnoreFeaturedSnippet string `json:"ignore_featured_snippet"`
	IgnoreInShareOfVoice  string `json:"ignore_in_share_of_voice"`
	IgnoreLocalResults    string `json:"ignore_local_results"`
	KeywordIds            string `json:"keyword_ids"`
	Starred               string `json:"starred"`
	Tags                  string `json:"tags"`
}

type LandingPageHistory struct {
	AboveTheFold                int             `json:"above_the_fold"`
	AiSearchVolume              int             `json:"ai_search_volume"`
	AiShareOfVoice              int             `json:"ai_share_of_voice"`
	AiTrafficValue              int             `json:"ai_traffic_value"`
	AverageCtr                  float64         `json:"average_ctr"`
	AverageCtrMax               float64         `json:"average_ctr_max"`
	AverageLocalPackRank        float64         `json:"average_local_pack_rank"`
	AverageRank                 float64         `json:"average_rank"`
	AvgBaseRank                 float64         `json:"avg_base_rank"`
	CommercialIntent            int             `json:"commercial_intent"`
	Date                        string          `json:"date"`
	EstimatedVisits             int             `json:"estimated_visits"`
	Ga4                         json.RawMessage `json:"ga4"`
	InformationalIntent         int             `json:"informational_intent"`
	Keywords                    int             `json:"keywords"`
	KeywordsWithAiOverview      int             `json:"keywords_with_ai_overview"`
	KeywordsWithAiOverviewOwned int             `json:"keywords_with_ai_overview_owned"`
	NavigationalIntent          int             `json:"navigational_intent"`
	PixelsFromTop               float64         `json:"pixels_from_top"`
	SearchVolume                int             `json:"search_volume"`
	ShareOfVoice                int             `json:"share_of_voice"`
	ShareOfVoicePercentage      float64         `json:"share_of_voice_percentage"`
	TrafficValue                int             `json:"traffic_value"`
	TransactionalIntent         int             `json:"transactional_intent"`
}

type LandingPageSerializerSchema struct {
	CreatedAt string          `json:"created_at"`
	History   json.RawMessage `json:"history"`
	Id        int             `json:"id"`
	Path      string          `json:"path"`
}

type Message struct {
	Message string `json:"message"`
}

type Organization struct {
	ApiFilters json.RawMessage `json:"api_filters"`
	Id         int             `json:"id"`
	Name       string          `json:"name"`
}

type PeopleAlso struct {
	LastSeenAt string `json:"last_seen_at"`
	Term       string `json:"term"`
}

type PreferredLandingPage struct {
	CreatedAt string `json:"created_at"`
	Id        int    `json:"id"`
	Path      string `json:"path"`
}

type Prompt struct {
	CountryCode string          `json:"country_code"`
	CreatedAt   string          `json:"created_at"`
	Description string          `json:"description"`
	Id          int             `json:"id"`
	Prompt      string          `json:"prompt"`
	Results     json.RawMessage `json:"results"`
	Starred     bool            `json:"starred"`
	Tags        json.RawMessage `json:"tags"`
}

type PromptIn struct {
	Countrylocale string          `json:"countrylocale"`
	Description   string          `json:"description"`
	DomainId      int             `json:"domain_id"`
	Prompts       json.RawMessage `json:"prompts"`
	Starred       bool            `json:"starred"`
	Tags          json.RawMessage `json:"tags"`
}

type PromptResults struct {
	Brands               json.RawMessage `json:"brands"`
	CreatedAt            string          `json:"created_at"`
	PromptResponse       string          `json:"prompt_response"`
	PromptResponseLength int             `json:"prompt_response_length"`
	RelatedPrompts       json.RawMessage `json:"related_prompts"`
	SearchEngine         string          `json:"search_engine"`
	Sources              json.RawMessage `json:"sources"`
	TopBrand             string          `json:"top_brand"`
	TopSource            string          `json:"top_source"`
}

type PromptSettings struct {
	Description string `json:"description"`
	DomainId    string `json:"domain_id"`
	PromptIds   string `json:"prompt_ids"`
	Starred     string `json:"starred"`
	Tags        string `json:"tags"`
}

type SearchEngine struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

type SearchSettings struct {
	Countrylocale     string          `json:"countrylocale"`
	Locations         json.RawMessage `json:"locations"`
	SearchEngineNames json.RawMessage `json:"search_engine_names"`
}

type SearchVolume struct {
	AvgCostPerClick         float64         `json:"avg_cost_per_click"`
	AvgCostPerClickCurrency string          `json:"avg_cost_per_click_currency"`
	Competition             float64         `json:"competition"`
	History                 json.RawMessage `json:"history"`
	Id                      int             `json:"id"`
	SearchVolume            int             `json:"search_volume"`
}

type SearchVolumeHistory struct {
	Date         string `json:"date"`
	SearchVolume int    `json:"search_volume"`
}

type Serps struct {
	Html string `json:"html"`
}

type Tag struct {
	History json.RawMessage `json:"history"`
	Tag     string          `json:"tag"`
}

type TagHistory struct {
	AboveTheFold                int     `json:"above_the_fold"`
	AiSearchVolume              int     `json:"ai_search_volume"`
	AiShareOfVoice              int     `json:"ai_share_of_voice"`
	AiTrafficValue              int     `json:"ai_traffic_value"`
	AverageCtr                  float64 `json:"average_ctr"`
	AverageCtrMax               float64 `json:"average_ctr_max"`
	AverageLocalPackRank        float64 `json:"average_local_pack_rank"`
	AverageRank                 float64 `json:"average_rank"`
	AvgBaseRank                 float64 `json:"avg_base_rank"`
	CommercialIntent            int     `json:"commercial_intent"`
	Date                        string  `json:"date"`
	EstimatedVisits             int     `json:"estimated_visits"`
	InformationalIntent         int     `json:"informational_intent"`
	Keywords                    int     `json:"keywords"`
	KeywordsWithAiOverview      int     `json:"keywords_with_ai_overview"`
	KeywordsWithAiOverviewOwned int     `json:"keywords_with_ai_overview_owned"`
	NavigationalIntent          int     `json:"navigational_intent"`
	PixelsFromTop               float64 `json:"pixels_from_top"`
	SearchVolume                int     `json:"search_volume"`
	ShareOfVoice                int     `json:"share_of_voice"`
	ShareOfVoicePercentage      float64 `json:"share_of_voice_percentage"`
	TrafficValue                int     `json:"traffic_value"`
	TransactionalIntent         int     `json:"transactional_intent"`
}
