// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — code-orchestration thin surface.
//
// Two tools cover the entire API: <api>_search to discover endpoints, and
// <api>_execute to invoke one. This collapses a large API (50+ endpoints)
// to ~1K tokens of tool definitions while preserving full coverage — the
// agent writes the composition logic in its own sandbox.
//
// Pattern source: Anthropic 2026-04-22 "Building agents that reach
// production systems with MCP" — Cloudflare's MCP server covers ~2,500
// endpoints in roughly 1K tokens via the same search+execute shape.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterCodeOrchestrationTools registers the two agent-facing tools that
// cover the whole API surface. Called from RegisterTools in place of the
// per-endpoint registrations when MCP.Orchestration is "code".
func RegisterCodeOrchestrationTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("accuranker_search",
			mcplib.WithDescription("Search the accuranker API for endpoints matching a natural-language query. Returns a ranked list of {endpoint_id, method, path, summary} entries. Call this first to find the endpoint to execute."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Natural-language description of what you want to do.")),
			mcplib.WithNumber("limit", mcplib.Description("Max endpoints to return (default 10).")),
		),
		handleCodeOrchSearch,
	)

	s.AddTool(
		mcplib.NewTool("accuranker_execute",
			mcplib.WithDescription("Execute one accuranker API endpoint by its endpoint_id (from accuranker_search). Params are passed as a JSON object; path placeholders and query strings are resolved automatically."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("Endpoint identifier returned by accuranker_search (e.g., \"users.list\").")),
			mcplib.WithObject("params", mcplib.Description("Parameters for the endpoint. Path placeholders match by name; remaining entries become query string on GET/DELETE or JSON body on POST/PUT/PATCH.")),
		),
		handleCodeOrchExecute,
	)
}

// codeOrchEndpoint captures the small slice of endpoint metadata the
// search+execute pair needs at runtime. `keywords` is a precomputed
// lowercase stream of description + path tokens used for naive ranking;
// anything more sophisticated belongs on the agent side.
type codeOrchEndpoint struct {
	ID         string
	Method     string
	Path       string
	Tier       string
	Summary    string
	Positional []string
	keywords   []string
}

// codeOrchEndpoints is the generator-populated registry covering every
// endpoint declared in the spec. Kept flat on purpose — the agent queries
// via <api>_search, so hierarchy shows up as dotted IDs, not nested maps.
var codeOrchEndpoints = []codeOrchEndpoint{
	{
		ID:         "accounts.create",
		Method:     "POST",
		Path:       "/api/v4/accounts/",
		Summary:    "POST with filters in body is equivalent to GET with filters. This enables complex filter queries without URL length...",
		Positional: []string{},
		keywords:   codeOrchKeywords("accounts", "create", "POST with filters in body is equivalent to GET with filters. This enables complex filter queries without URL length...", "/api/v4/accounts/"),
	},
	{
		ID:         "accounts.get",
		Method:     "GET",
		Path:       "/api/v4/accounts/{id}/",
		Summary:    "Get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("accounts", "get", "Get", "/api/v4/accounts/{id}/"),
	},
	{
		ID:         "accounts.list",
		Method:     "GET",
		Path:       "/api/v4/accounts/",
		Summary:    "List",
		Positional: []string{},
		keywords:   codeOrchKeywords("accounts", "list", "List", "/api/v4/accounts/"),
	},
	{
		ID:         "brand.create",
		Method:     "POST",
		Path:       "/api/v4/brand/",
		Summary:    "This endpoint creates a new brand for your group. A brand can only be created on groups or subaccounts authorized by...",
		Positional: []string{},
		keywords:   codeOrchKeywords("brand", "create", "This endpoint creates a new brand for your group. A brand can only be created on groups or subaccounts authorized by...", "/api/v4/brand/"),
	},
	{
		ID:         "brand.delete",
		Method:     "DELETE",
		Path:       "/api/v4/brand/{brand_id}",
		Summary:    "This endpoint deletes a brand and all underlying prompts - hence use this endpoint with caution. Curl example: curl...",
		Positional: []string{"brand_id"},
		keywords:   codeOrchKeywords("brand", "delete", "This endpoint deletes a brand and all underlying prompts - hence use this endpoint with caution. Curl example: curl...", "/api/v4/brand/{brand_id}"),
	},
	{
		ID:         "brand.update",
		Method:     "PUT",
		Path:       "/api/v4/brand/{brand_id}",
		Summary:    "This endpoint updates a brand in your group. All fields are optional. If you leave a field out, the value will not...",
		Positional: []string{"brand_id"},
		keywords:   codeOrchKeywords("brand", "update", "This endpoint updates a brand in your group. All fields are optional. If you leave a field out, the value will not...", "/api/v4/brand/{brand_id}"),
	},
	{
		ID:         "brands.get",
		Method:     "GET",
		Path:       "/api/v4/brands/{id}/",
		Summary:    "Get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("brands", "get", "Get", "/api/v4/brands/{id}/"),
	},
	{
		ID:         "brands.list",
		Method:     "GET",
		Path:       "/api/v4/brands/",
		Summary:    "List",
		Positional: []string{},
		keywords:   codeOrchKeywords("brands", "list", "List", "/api/v4/brands/"),
	},
	{
		ID:         "brands.list-with-filters",
		Method:     "POST",
		Path:       "/api/v4/brands/",
		Summary:    "POST alternative to GET with filters in request body. Useful for complex filter queries.",
		Positional: []string{},
		keywords:   codeOrchKeywords("brands", "list-with-filters", "POST alternative to GET with filters in request body. Useful for complex filter queries.", "/api/v4/brands/"),
	},
	{
		ID:         "brands.prompts.get",
		Method:     "GET",
		Path:       "/api/v4/brands/{brands_pk}/prompts/{id}/",
		Summary:    "Get",
		Positional: []string{"id", "brands_pk"},
		keywords:   codeOrchKeywords("brands", "get", "Get", "/api/v4/brands/{brands_pk}/prompts/{id}/"),
	},
	{
		ID:         "brands.prompts.list",
		Method:     "GET",
		Path:       "/api/v4/brands/{brands_pk}/prompts/",
		Summary:    "List",
		Positional: []string{"brands_pk"},
		keywords:   codeOrchKeywords("brands", "list", "List", "/api/v4/brands/{brands_pk}/prompts/"),
	},
	{
		ID:         "brands.prompts.list-with-filters",
		Method:     "POST",
		Path:       "/api/v4/brands/{brands_pk}/prompts/",
		Summary:    "POST alternative to GET with filters in request body. Useful for complex filter queries.",
		Positional: []string{"brands_pk"},
		keywords:   codeOrchKeywords("brands", "list-with-filters", "POST alternative to GET with filters in request body. Useful for complex filter queries.", "/api/v4/brands/{brands_pk}/prompts/"),
	},
	{
		ID:         "domain.create",
		Method:     "POST",
		Path:       "/api/v4/domain/",
		Summary:    "This endpoint creates a new domain for your group. A domain can only be created on groups or subaccounts authorized...",
		Positional: []string{},
		keywords:   codeOrchKeywords("domain", "create", "This endpoint creates a new domain for your group. A domain can only be created on groups or subaccounts authorized...", "/api/v4/domain/"),
	},
	{
		ID:         "domain.delete",
		Method:     "DELETE",
		Path:       "/api/v4/domain/{domain_id}",
		Summary:    "This endpoint deletes a domain and all underlying keywordss - hence use this endpoint with caution. Curl example:...",
		Positional: []string{"domain_id"},
		keywords:   codeOrchKeywords("domain", "delete", "This endpoint deletes a domain and all underlying keywordss - hence use this endpoint with caution. Curl example:...", "/api/v4/domain/{domain_id}"),
	},
	{
		ID:         "domain.update",
		Method:     "PUT",
		Path:       "/api/v4/domain/{domain_id}",
		Summary:    "This endpoint updates a domain in your group. All fields are optional. If you leave a field out, the value will not...",
		Positional: []string{"domain_id"},
		keywords:   codeOrchKeywords("domain", "update", "This endpoint updates a domain in your group. All fields are optional. If you leave a field out, the value will not...", "/api/v4/domain/{domain_id}"),
	},
	{
		ID:         "domains.get",
		Method:     "GET",
		Path:       "/api/v4/domains/{id}/",
		Summary:    "Get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("domains", "get", "Get", "/api/v4/domains/{id}/"),
	},
	{
		ID:         "domains.list",
		Method:     "GET",
		Path:       "/api/v4/domains/",
		Summary:    "List",
		Positional: []string{},
		keywords:   codeOrchKeywords("domains", "list", "List", "/api/v4/domains/"),
	},
	{
		ID:         "domains.list-with-filters",
		Method:     "POST",
		Path:       "/api/v4/domains/",
		Summary:    "POST alternative to GET with filters in request body. Useful for complex filter queries.",
		Positional: []string{},
		keywords:   codeOrchKeywords("domains", "list-with-filters", "POST alternative to GET with filters in request body. Useful for complex filter queries.", "/api/v4/domains/"),
	},
	{
		ID:         "domains.keywords.get",
		Method:     "GET",
		Path:       "/api/v4/domains/{domain_pk}/keywords/{id}/",
		Summary:    "Get",
		Positional: []string{"id", "domain_pk"},
		keywords:   codeOrchKeywords("domains", "get", "Get", "/api/v4/domains/{domain_pk}/keywords/{id}/"),
	},
	{
		ID:         "domains.keywords.get-html",
		Method:     "GET",
		Path:       "/api/v4/domains/{domain_pk}/keywords/{keyword_pk}/ranks/{search_date}/",
		Summary:    "Get html",
		Positional: []string{"domain_pk", "keyword_pk", "search_date"},
		keywords:   codeOrchKeywords("domains", "get-html", "Get html", "/api/v4/domains/{domain_pk}/keywords/{keyword_pk}/ranks/{search_date}/"),
	},
	{
		ID:         "domains.keywords.list",
		Method:     "GET",
		Path:       "/api/v4/domains/{domain_pk}/keywords/",
		Summary:    "List",
		Positional: []string{"domain_pk"},
		keywords:   codeOrchKeywords("domains", "list", "List", "/api/v4/domains/{domain_pk}/keywords/"),
	},
	{
		ID:         "domains.keywords.list-with-filters",
		Method:     "POST",
		Path:       "/api/v4/domains/{domain_pk}/keywords/",
		Summary:    "POST alternative to GET with filters in request body. Useful for complex filter queries.",
		Positional: []string{"domain_pk"},
		keywords:   codeOrchKeywords("domains", "list-with-filters", "POST alternative to GET with filters in request body. Useful for complex filter queries.", "/api/v4/domains/{domain_pk}/keywords/"),
	},
	{
		ID:         "domains.landing-pages.get",
		Method:     "GET",
		Path:       "/api/v4/domains/{domain_pk}/landing_pages/{id}/",
		Summary:    "Get",
		Positional: []string{"id", "domain_pk"},
		keywords:   codeOrchKeywords("domains", "get", "Get", "/api/v4/domains/{domain_pk}/landing_pages/{id}/"),
	},
	{
		ID:         "domains.landing-pages.list",
		Method:     "GET",
		Path:       "/api/v4/domains/{domain_pk}/landing_pages/",
		Summary:    "List",
		Positional: []string{"domain_pk"},
		keywords:   codeOrchKeywords("domains", "list", "List", "/api/v4/domains/{domain_pk}/landing_pages/"),
	},
	{
		ID:         "domains.landing-pages.list-with-filters",
		Method:     "POST",
		Path:       "/api/v4/domains/{domain_pk}/landing_pages/",
		Summary:    "POST alternative to GET with filters in request body. Useful for complex filter queries.",
		Positional: []string{"domain_pk"},
		keywords:   codeOrchKeywords("domains", "list-with-filters", "POST alternative to GET with filters in request body. Useful for complex filter queries.", "/api/v4/domains/{domain_pk}/landing_pages/"),
	},
	{
		ID:         "domains.tags.list",
		Method:     "GET",
		Path:       "/api/v4/domains/{domain_pk}/tags/",
		Summary:    "List",
		Positional: []string{"domain_pk"},
		keywords:   codeOrchKeywords("domains", "list", "List", "/api/v4/domains/{domain_pk}/tags/"),
	},
	{
		ID:         "domains.tags.list-with-filters",
		Method:     "POST",
		Path:       "/api/v4/domains/{domain_pk}/tags/",
		Summary:    "POST alternative to GET with filters in request body. Useful for complex filter queries.",
		Positional: []string{"domain_pk"},
		keywords:   codeOrchKeywords("domains", "list-with-filters", "POST alternative to GET with filters in request body. Useful for complex filter queries.", "/api/v4/domains/{domain_pk}/tags/"),
	},
	{
		ID:         "group.create",
		Method:     "POST",
		Path:       "/api/v4/group/",
		Summary:    "This endpoint creates a new group on your account. The group can only be created on accounts or subaccounts...",
		Positional: []string{},
		keywords:   codeOrchKeywords("group", "create", "This endpoint creates a new group on your account. The group can only be created on accounts or subaccounts...", "/api/v4/group/"),
	},
	{
		ID:         "group.delete",
		Method:     "DELETE",
		Path:       "/api/v4/group/{group_id}",
		Summary:    "This endpoint deletes a group and all underlying domains and keywords - hence use this endpoint with caution. Curl...",
		Positional: []string{"group_id"},
		keywords:   codeOrchKeywords("group", "delete", "This endpoint deletes a group and all underlying domains and keywords - hence use this endpoint with caution. Curl...", "/api/v4/group/{group_id}"),
	},
	{
		ID:         "group.update",
		Method:     "PUT",
		Path:       "/api/v4/group/{group_id}",
		Summary:    "This endpoint updates a group for your account. Only groups on accounts or subaccounts authorized by the token can...",
		Positional: []string{"group_id"},
		keywords:   codeOrchKeywords("group", "update", "This endpoint updates a group for your account. Only groups on accounts or subaccounts authorized by the token can...", "/api/v4/group/{group_id}"),
	},
	{
		ID:         "keyword.create",
		Method:     "POST",
		Path:       "/api/v4/keyword/",
		Summary:    "With this endpoint, you can create one or more keywords on a domain. Keywords can only be created on domains...",
		Positional: []string{},
		keywords:   codeOrchKeywords("keyword", "create", "With this endpoint, you can create one or more keywords on a domain. Keywords can only be created on domains...", "/api/v4/keyword/"),
	},
	{
		ID:         "keyword.delete",
		Method:     "DELETE",
		Path:       "/api/v4/keyword/",
		Summary:    "This endpoint deletes is used to delete a keyword - hence you should use this with caution. Curl example: curl -X...",
		Positional: []string{},
		keywords:   codeOrchKeywords("keyword", "delete", "This endpoint deletes is used to delete a keyword - hence you should use this with caution. Curl example: curl -X...", "/api/v4/keyword/"),
	},
	{
		ID:         "keyword.update",
		Method:     "PUT",
		Path:       "/api/v4/keyword/",
		Summary:    "This endpoint updates settings for the given keywords. Only keywords on domains authorized by the token can be...",
		Positional: []string{},
		keywords:   codeOrchKeywords("keyword", "update", "This endpoint updates settings for the given keywords. Only keywords on domains authorized by the token can be...", "/api/v4/keyword/"),
	},
	{
		ID:         "overview.get-group-and-domains",
		Method:     "GET",
		Path:       "/api/v4/overview/group_domains",
		Summary:    "This endpoint returns a list of all accounts, groups and domains for your account. The list is based on the token...",
		Positional: []string{},
		keywords:   codeOrchKeywords("overview", "get-group-and-domains", "This endpoint returns a list of all accounts, groups and domains for your account. The list is based on the token...", "/api/v4/overview/group_domains"),
	},
	{
		ID:         "overview.get-keyword-for-domain",
		Method:     "GET",
		Path:       "/api/v4/overview/keywords_for_domain/{domain_id}",
		Summary:    "This endpoint returns a list of all your keywords on the provided domain. Curl example: curl -X GET -H...",
		Positional: []string{"domain_id"},
		keywords:   codeOrchKeywords("overview", "get-keyword-for-domain", "This endpoint returns a list of all your keywords on the provided domain. Curl example: curl -X GET -H...", "/api/v4/overview/keywords_for_domain/{domain_id}"),
	},
	{
		ID:         "prompt.create",
		Method:     "POST",
		Path:       "/api/v4/prompt/",
		Summary:    "With this endpoint, you can create one or more prompts on a brand. Prompts can only be created on brands authorized...",
		Positional: []string{},
		keywords:   codeOrchKeywords("prompt", "create", "With this endpoint, you can create one or more prompts on a brand. Prompts can only be created on brands authorized...", "/api/v4/prompt/"),
	},
	{
		ID:         "prompt.delete",
		Method:     "DELETE",
		Path:       "/api/v4/prompt/",
		Summary:    "This endpoint deletes is used to delete a prompt - hence you should use this with caution. Curl example: curl -X...",
		Positional: []string{},
		keywords:   codeOrchKeywords("prompt", "delete", "This endpoint deletes is used to delete a prompt - hence you should use this with caution. Curl example: curl -X...", "/api/v4/prompt/"),
	},
	{
		ID:         "prompt.update",
		Method:     "PUT",
		Path:       "/api/v4/prompt/",
		Summary:    "This endpoint updates settings for the given prompts. Only prompts on domains authorized by the token can be...",
		Positional: []string{},
		keywords:   codeOrchKeywords("prompt", "update", "This endpoint updates settings for the given prompts. Only prompts on domains authorized by the token can be...", "/api/v4/prompt/"),
	},
	{
		ID:         "status.keyword-job",
		Method:     "GET",
		Path:       "/api/v4/status/keyword_job/{job_id}",
		Summary:    "Return status of an keyword job, given a job ID. To start a job call POST or PUT /keyword. Any response code other...",
		Positional: []string{"job_id"},
		keywords:   codeOrchKeywords("status", "keyword-job", "Return status of an keyword job, given a job ID. To start a job call POST or PUT /keyword. Any response code other...", "/api/v4/status/keyword_job/{job_id}"),
	},
}

// codeOrchStopwords filters two-letter and short common-word substrings
// that pollute ranking via the substring-contains rule. Without them, a
// search for "list links" matches every endpoint whose description
// contains "is enrolled" because "is" is two chars and the matcher
// accepts kw.contains(t) || t.contains(kw).
var codeOrchStopwords = map[string]bool{
	"a": true, "an": true, "and": true, "are": true, "as": true,
	"at": true, "be": true, "by": true, "for": true, "from": true,
	"has": true, "in": true, "is": true, "it": true, "its": true,
	"of": true, "on": true, "or": true, "that": true, "the": true,
	"this": true, "to": true, "was": true, "will": true, "with": true,
	"your": true, "you": true, "any": true, "all": true,
}

// codeOrchKeywords produces the lowercase token stream used for search
// ranking. Defined at package level so the registry initializer can call it
// inline above without pulling in a separate precompute step.
func codeOrchKeywords(resource, endpoint, summary, path string) []string {
	raw := strings.ToLower(resource + " " + endpoint + " " + summary + " " + path)
	raw = strings.Map(func(r rune) rune {
		switch r {
		case '_', '-', '/', '{', '}', '.', ',', ':', ';':
			return ' '
		}
		return r
	}, raw)
	out := make([]string, 0, 16)
	seen := map[string]bool{}
	for _, tok := range strings.Fields(raw) {
		if len(tok) < 3 || codeOrchStopwords[tok] || seen[tok] {
			continue
		}
		seen[tok] = true
		out = append(out, tok)
	}
	return out
}

func handleCodeOrchSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || strings.TrimSpace(query) == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	limit := 10
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	terms := codeOrchKeywords("", "", query, "")
	type scored struct {
		ep    *codeOrchEndpoint
		score int
	}
	results := make([]scored, 0, len(codeOrchEndpoints))
	for i := range codeOrchEndpoints {
		ep := &codeOrchEndpoints[i]
		score := 0
		for _, t := range terms {
			for _, kw := range ep.keywords {
				if kw == t {
					score += 2
				} else if strings.Contains(kw, t) || strings.Contains(t, kw) {
					score++
				}
			}
		}
		if score > 0 {
			results = append(results, scored{ep: ep, score: score})
		}
	}
	sort.SliceStable(results, func(i, j int) bool { return results[i].score > results[j].score })
	if len(results) > limit {
		results = results[:limit]
	}

	out := make([]map[string]any, 0, len(results))
	for _, r := range results {
		out = append(out, map[string]any{
			"endpoint_id": r.ep.ID,
			"method":      r.ep.Method,
			"path":        r.ep.Path,
			"summary":     r.ep.Summary,
			"score":       r.score,
		})
	}
	data, _ := json.Marshal(map[string]any{"count": len(out), "results": out})
	return mcplib.NewToolResultText(string(data)), nil
}

func handleCodeOrchExecute(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call accuranker_search first)"), nil
	}

	var ep *codeOrchEndpoint
	for i := range codeOrchEndpoints {
		if codeOrchEndpoints[i].ID == id {
			ep = &codeOrchEndpoints[i]
			break
		}
	}
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call accuranker_search to discover valid ids", id)), nil
	}

	params, _ := args["params"].(map[string]any)
	if params == nil {
		params = map[string]any{}
	}

	c, err := newMCPClient()
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path := ep.Path
	for _, p := range ep.Positional {
		if v, ok := params[p]; ok {
			path = strings.ReplaceAll(path, "{"+p+"}", fmt.Sprintf("%v", v))
			delete(params, p)
		}
	}

	// Code-orch dispatch has no schema metadata at runtime to bucket params
	// into body vs query, so POST/PUT/PATCH keep the everything-to-body
	// design. DELETE is the one verb where query routing is unambiguous; the
	// previous code built `query` but never passed it.
	query := map[string]string{}
	if ep.Method == "GET" || ep.Method == "DELETE" {
		for k, v := range params {
			query[k] = fmt.Sprintf("%v", v)
		}
	}

	var data json.RawMessage
	switch ep.Method {
	case "GET":
		data, err = c.Get(path, query)
	case "DELETE":
		data, _, err = c.DeleteWithParams(path, query)
	case "POST":
		data, _, err = c.Post(path, params)
	case "PUT":
		data, _, err = c.Put(path, params)
	case "PATCH":
		data, _, err = c.Patch(path, params)
	default:
		return mcplib.NewToolResultError(fmt.Sprintf("unsupported method %q", ep.Method)), nil
	}
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}
