// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"accuranker-pp-cli/internal/cli"
	"accuranker-pp-cli/internal/client"
	"accuranker-pp-cli/internal/cliutil"
	"accuranker-pp-cli/internal/config"
	"accuranker-pp-cli/internal/mcp/cobratree"
	"accuranker-pp-cli/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	// Code-orchestration mode — the full surface is covered by two tools
	// (<api>_search + <api>_execute). Endpoint-mirror tools are suppressed.
	RegisterCodeOrchestrationTools(s)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, binaryResponse bool, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if binaryResponse {
			headers = map[string]string{client.BinaryResponseHeader: "true"}
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if binaryResponse {
				data, err = c.GetWithHeaders(path, params, headers)
				break
			}
			data, err = c.Get(path, params)
		case "POST":
			if binaryResponse {
				data, _, err = c.PostWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PostWithParams(path, params, bodyArgs)
		case "PUT":
			if binaryResponse {
				data, _, err = c.PutWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(path, params, bodyArgs)
		case "PATCH":
			if binaryResponse {
				data, _, err = c.PatchWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(path, params, bodyArgs)
		case "DELETE":
			if binaryResponse {
				data, _, err = c.DeleteWithParamsAndHeaders(path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export ACCURANKER_API_TOKEN=<your-key>" +
					"\n      Get a key at: https://app.accuranker.com/app/profile" +
					"\n      Run 'accuranker-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set it with: export ACCURANKER_API_TOKEN=<your-key>" +
					"\n      Get a key at: https://app.accuranker.com/app/profile" +
					"\n      Run 'accuranker-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export ACCURANKER_API_TOKEN=<your-key>" +
					"\n      Get a key at: https://app.accuranker.com/app/profile" +
					"\n      Run 'accuranker-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "accuranker-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "accuranker-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "accuranker",
		"description": "The first real CLI for AccuRanker — built to feed your warehouse and your AI agents, not to ship dashboards.",
		"archetype":   "content",
		"tool_count":  39,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion accuranker-pp-cli binary.",
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []map[string]any{
				{
					"name":        "ACCURANKER_API_TOKEN",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
			"key_url": "https://app.accuranker.com/app/profile",
		},
		"resources": []map[string]any{
			{
				"name":        "accounts",
				"description": "List/get accounts associated with the caller's API token",
				"endpoints":   []string{"create", "get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "brand",
				"description": "AccuLLM brands. Requires LLM API plan tier.",
				"endpoints":   []string{"create", "delete", "update"},
				"searchable":  true,
			},
			{
				"name":        "brands",
				"description": "AccuLLM brands. Requires LLM API plan tier.",
				"endpoints":   []string{"get", "list", "list-with-filters"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "domain",
				"description": "List, get, create, update, delete domains. Domain payloads include 24-field DomainHistory time-series when...",
				"endpoints":   []string{"create", "delete", "update"},
				"searchable":  true,
			},
			{
				"name":        "domains",
				"description": "List, get, create, update, delete domains. Domain payloads include 24-field DomainHistory time-series when...",
				"endpoints":   []string{"get", "list", "list-with-filters"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "group",
				"description": "Write API: groups ('Clients') that contain domains.",
				"endpoints":   []string{"create", "delete", "update"},
				"searchable":  true,
			},
			{
				"name":        "keyword",
				"description": "Read keyword ranks (highest-cardinality data). Supports period windows and dynamic filters. Write side supports bulk...",
				"endpoints":   []string{"create", "delete", "update"},
				"searchable":  true,
			},
			{
				"name":        "overview",
				"description": "High-level account overview. Requires additional plan tier.",
				"endpoints":   []string{"get-group-and-domains", "get-keyword-for-domain"},
				"searchable":  true,
			},
			{
				"name":        "prompt",
				"description": "AccuLLM prompts. Requires LLM API plan tier.",
				"endpoints":   []string{"create", "delete", "update"},
				"searchable":  true,
			},
			{
				"name":        "status",
				"description": "Manage status",
				"endpoints":   []string{"keyword-job"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass offset parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Typed v2-aligned mirror into local SQLite", "command": "mirror", "description": "Sync a domain's data into typed SQLite tables that match schema/model.yaml exactly — keywords, keyword_ranks,...", "rationale": "The press's generic `sync` writes to one generic `resources` table; the v2 Postgres mirror needs typed tables....", "via": "mcp-command-mirror"},
			{"name": "NDJSON dump with auto-chunked window", "command": "dump", "description": "Stream historical rank or domain-history data over any window. The CLI walks 100-day slices internally and dedups,...", "rationale": "The API refuses date ranges over 100 days; the only tool that abstracts that constraint is this one. NDJSON is ready...", "via": "mcp-command-mirror"},
			{"name": "Machine-readable schema for v2 mirror", "command": "schema", "description": "Print the canonical data shape — every resource, field, filter dimension, comparator legality, and sync hint —...", "rationale": "Building a Postgres mirror from scratch requires knowing every field name, type, and FK relationship. The API has no...", "via": "mcp-command-mirror"},
			{"name": "Discoverable filter dimensions", "command": "filters list", "description": "List all 100+ filter dimensions AccuRanker accepts in dynamic filter expressions, with type class and accepted...", "rationale": "AccuRanker's filter DSL has 100+ named dimensions and not every comparator is legal for every dimension. The...", "via": "mcp-command-mirror"},
			{"name": "SERP-feature gain/loss delta", "command": "serp-features delta", "description": "Partition a domain's keywords into gained / lost / held for any SERP feature (AI Overview, featured snippet, local...", "rationale": "AccuRanker's server-side filter answers `has_ai_overview eq true`, not `gained ai_overview between dates`. The delta...", "via": "mcp-command-mirror"},
			{"name": "Cannibalization detection", "command": "cannibalize", "description": "Flag keywords where multiple URLs from the same domain rank simultaneously, or where the highest-ranking page flips...", "rationale": "The API exposes `extra_ranks` (a per-rank array of competing URLs from the same domain) and `highest_ranking_page`...", "via": "mcp-command-mirror"},
			{"name": "Decay opportunity finder", "command": "decay", "description": "Find keywords whose rank is getting worse while their search volume is climbing — the classic 'losing ground on...", "rationale": "Requires joining `keyword_ranks` (daily rank time-series) with `search_volume_history` (monthly volume time-series),...", "via": "mcp-command-mirror"},
			{"name": "Keyword spec diff before apply", "command": "keywords-diff", "description": "Compare a local CSV/NDJSON keyword spec against AccuRanker's current keyword list. Emits adds/removes/updates...", "rationale": "The AccuRanker UI has no dry-run for keyword imports; it silently truncates large pastes. A diff command is the only...", "via": "mcp-command-mirror"},
			{"name": "Push local mirror to remote Postgres", "command": "push", "description": "Upsert every table from the local SQLite mirror into a remote Postgres schema using DDL derived from...", "rationale": "Postgres-mirror downstream services need a tested handoff. The CLI ships schema/model.yaml as the canonical...", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Typed v2-aligned mirror into local SQLite", "insight": "The press's generic `sync` writes to one generic `resources` table; the v2 Postgres mirror needs typed tables. `mirror` reads schema/model.yaml, fills `fields=` automatically, walks date windows, and writes to the typed tables that `push` then exports to Postgres. This is the v2 pattern in v1 form."},
			{"topic": "NDJSON dump with auto-chunked window", "insight": "The API refuses date ranges over 100 days; the only tool that abstracts that constraint is this one. NDJSON is ready to pipe into `psql COPY` or any line-oriented loader."},
			{"topic": "Machine-readable schema for v2 mirror", "insight": "Building a Postgres mirror from scratch requires knowing every field name, type, and FK relationship. The API has no /schema endpoint; we built one from the model that drives the CLI itself."},
			{"topic": "Discoverable filter dimensions", "insight": "AccuRanker's filter DSL has 100+ named dimensions and not every comparator is legal for every dimension. The upstream docs are a Markdown table; we make it a queryable CLI subtree so agents and humans can build filter expressions without re-reading docs."},
			{"topic": "SERP-feature gain/loss delta", "insight": "AccuRanker's server-side filter answers `has_ai_overview eq true`, not `gained ai_overview between dates`. The delta requires comparing two snapshots — only possible against the synced local mirror."},
			{"topic": "Cannibalization detection", "insight": "The API exposes `extra_ranks` (a per-rank array of competing URLs from the same domain) and `highest_ranking_page` (which URL won today). Detecting the anti-pattern requires joining both across time — a local SQL transformation."},
			{"topic": "Decay opportunity finder", "insight": "Requires joining `keyword_ranks` (daily rank time-series) with `search_volume_history` (monthly volume time-series), partitioning trends with window functions. No single API endpoint correlates these."},
			{"topic": "Keyword spec diff before apply", "insight": "The AccuRanker UI has no dry-run for keyword imports; it silently truncates large pastes. A diff command is the only safe way to script bulk keyword operations against multiple clients."},
			{"topic": "Push local mirror to remote Postgres", "insight": "Postgres-mirror downstream services need a tested handoff. The CLI ships schema/model.yaml as the canonical contract; `push` reads that file, ensures the target schema exists, and full-table upserts. MVP only; incremental and cursor-aware push are documented as v1.1 extension points."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
