// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "accounts",
		Short:  "List/get accounts associated with the caller's API token",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAccountsCreateCmd(flags))
	cmd.AddCommand(newAccountsGetCmd(flags))
	cmd.AddCommand(newAccountsListCmd(flags))
	return cmd
}
