// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAccountsCreateCmd(flags *rootFlags) *cobra.Command {
	var flagFields string
	var flagPeriodFrom string
	var flagPeriodTo string
	var flagFilterId string
	var bodyApiFilters string
	var bodyId int
	var bodyName string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "POST with filters in body is equivalent to GET with filters. This enables complex filter queries without URL length...",
		Example:     "  accuranker-pp-cli accounts create",
		Annotations: map[string]string{"pp:endpoint": "accounts.create", "pp:method": "POST", "pp:path": "/api/v4/accounts/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v4/accounts/"
			params := map[string]string{}
			if flagFields != "" {
				params["fields"] = fmt.Sprintf("%v", flagFields)
			}
			if flagPeriodFrom != "" {
				params["period_from"] = fmt.Sprintf("%v", flagPeriodFrom)
			}
			if flagPeriodTo != "" {
				params["period_to"] = fmt.Sprintf("%v", flagPeriodTo)
			}
			if flagFilterId != "" {
				params["filter_id"] = fmt.Sprintf("%v", flagFilterId)
			}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyApiFilters != "" {
					var parsedApiFilters any
					if err := json.Unmarshal([]byte(bodyApiFilters), &parsedApiFilters); err != nil {
						return fmt.Errorf("parsing --api-filters JSON: %w", err)
					}
					body["api_filters"] = parsedApiFilters
				}
				if bodyId != 0 {
					body["id"] = bodyId
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
			}
			data, statusCode, err := c.PostWithParams(path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "accounts", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
					}
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "accounts",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&flagFields, "fields", "", "GraphQL-like field projection (dot notation). EXAMPLE: 'id,keyword,ranks.rank,ranks.created_at'. Without this...")
	cmd.Flags().StringVar(&flagPeriodFrom, "period-from", "", "Historical window start (YYYY-MM-DD, inclusive). Pair with period_to. Max 100 days between from/to.")
	cmd.Flags().StringVar(&flagPeriodTo, "period-to", "", "Historical window end (YYYY-MM-DD, inclusive). Pair with period_from. Max 100 days between from/to.")
	cmd.Flags().StringVar(&flagFilterId, "filter-id", "", "Saved API-filter ID (segments marked as 'API filter' in AccuRanker > Integrations > API).")
	cmd.Flags().StringVar(&bodyApiFilters, "api-filters", "", "Api filters")
	cmd.Flags().IntVar(&bodyId, "id", 0, "Id")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of your account/department. This will show up on reports.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
