// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBrandCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "brand",
		Short:  "AccuLLM brands. Requires LLM API plan tier.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBrandCreateCmd(flags))
	cmd.AddCommand(newBrandDeleteCmd(flags))
	cmd.AddCommand(newBrandUpdateCmd(flags))
	return cmd
}
