// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBrandsPromptsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "prompts",
		Short: "AccuLLM prompts. Requires LLM API plan tier.",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBrandsPromptsGetCmd(flags))
	cmd.AddCommand(newBrandsPromptsListCmd(flags))
	cmd.AddCommand(newBrandsPromptsListWithFiltersCmd(flags))
	return cmd
}
