// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDomainsLandingPagesGetCmd(flags *rootFlags) *cobra.Command {
	var flagFields string
	var flagPeriodFrom string
	var flagPeriodTo string
	var flagFilterId string

	cmd := &cobra.Command{
		Use:         "get <id> <domain_pk>",
		Short:       "Get",
		Example:     "  accuranker-pp-cli domains landing-pages get 550e8400-e29b-41d4-a716-446655440000 example-value",
		Annotations: map[string]string{"pp:endpoint": "landing-pages.get", "pp:method": "GET", "pp:path": "/api/v4/domains/{domain_pk}/landing_pages/{id}/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v4/domains/{domain_pk}/landing_pages/{id}/"
			path = replacePathParam(path, "id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("domain_pk is required\nUsage: %s <%s>", cmd.CommandPath(), "domain_pk"))
			}
			path = replacePathParam(path, "domain_pk", args[1])
			params := map[string]string{}
			if flagFields != "" {
				params["fields"] = fmt.Sprintf("%v", flagFields)
			}
			if flagPeriodFrom != "" {
				params["period_from"] = fmt.Sprintf("%v", flagPeriodFrom)
			}
			if flagPeriodTo != "" {
				params["period_to"] = fmt.Sprintf("%v", flagPeriodTo)
			}
			if flagFilterId != "" {
				params["filter_id"] = fmt.Sprintf("%v", flagFilterId)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "landing-pages", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagFields, "fields", "", "Comma separated string (`?fields=id,keyword,n...`) describing the fields you wish to return on the object. For...")
	cmd.Flags().StringVar(&flagPeriodFrom, "period-from", "", "Date in format: YYYY-MM-DD.")
	cmd.Flags().StringVar(&flagPeriodTo, "period-to", "", "Date in format: YYYY-MM-DD.")
	cmd.Flags().StringVar(&flagFilterId, "filter-id", "", "The ID of a saved API filter/segment. You can find your API filters at /app/integrations/api.")

	return cmd
}
