// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDomainsKeywordsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "keywords",
		Short: "Read keyword ranks (highest-cardinality data). Supports period windows and dynamic filters. Write side supports bulk...",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDomainsKeywordsGetCmd(flags))
	cmd.AddCommand(newDomainsKeywordsGetHtmlCmd(flags))
	cmd.AddCommand(newDomainsKeywordsListCmd(flags))
	cmd.AddCommand(newDomainsKeywordsListWithFiltersCmd(flags))
	return cmd
}
