// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDomainsTagsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tags",
		Short: "Aggregated metrics per keyword tag.",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDomainsTagsListCmd(flags))
	cmd.AddCommand(newDomainsTagsListWithFiltersCmd(flags))
	return cmd
}
