// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDomainsLandingPagesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "landing-pages",
		Short: "Aggregated metrics per landing page (URL).",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDomainsLandingPagesGetCmd(flags))
	cmd.AddCommand(newDomainsLandingPagesListCmd(flags))
	cmd.AddCommand(newDomainsLandingPagesListWithFiltersCmd(flags))
	return cmd
}
