// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDomainsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "domains",
		Short:  "List, get, create, update, delete domains. Domain payloads include 24-field DomainHistory time-series when...",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDomainsGetCmd(flags))
	cmd.AddCommand(newDomainsListCmd(flags))
	cmd.AddCommand(newDomainsListWithFiltersCmd(flags))
	cmd.AddCommand(newDomainsKeywordsCmd(flags))
	cmd.AddCommand(newDomainsLandingPagesCmd(flags))
	cmd.AddCommand(newDomainsTagsCmd(flags))
	return cmd
}
