// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newDomainCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyDefaultSearchsettingsNames string
	var bodyDisplayName string
	var bodyDomain string
	var bodyExactMatch bool
	var bodyFacebookProfile string
	var bodyGoogleBusinessNameList string
	var bodyGroupId int
	var bodyIncludeSubdomains bool
	var bodyInstagramProfile string
	var bodyLinkedinProfile string
	var bodyShareOfVoicePercentage bool
	var bodyTiktokProfile string
	var bodyXHandle string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "This endpoint creates a new domain for your group. A domain can only be created on groups or subaccounts authorized...",
		Example:     "  accuranker-pp-cli domain create --domain example-value",
		Annotations: map[string]string{"pp:endpoint": "domain.create", "pp:method": "POST", "pp:path": "/api/v4/domain/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("default-searchsettings-names") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "default-searchsettings-names")
				}
				if !cmd.Flags().Changed("domain") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "domain")
				}
				if !cmd.Flags().Changed("group-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "group-id")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v4/domain/"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyDefaultSearchsettingsNames != "" {
					var parsedDefaultSearchsettingsNames any
					if err := json.Unmarshal([]byte(bodyDefaultSearchsettingsNames), &parsedDefaultSearchsettingsNames); err != nil {
						return fmt.Errorf("parsing --default-searchsettings-names JSON: %w", err)
					}
					body["default_searchsettings_names"] = parsedDefaultSearchsettingsNames
				}
				if bodyDisplayName != "" {
					body["display_name"] = bodyDisplayName
				}
				if bodyDomain != "" {
					body["domain"] = bodyDomain
				}
				if cmd.Flags().Changed("exact-match") {
					body["exact_match"] = bodyExactMatch
				}
				if bodyFacebookProfile != "" {
					body["facebook_profile"] = bodyFacebookProfile
				}
				if bodyGoogleBusinessNameList != "" {
					body["google_business_name_list"] = bodyGoogleBusinessNameList
				}
				if bodyGroupId != 0 {
					body["group_id"] = bodyGroupId
				}
				if cmd.Flags().Changed("include-subdomains") {
					body["include_subdomains"] = bodyIncludeSubdomains
				}
				if bodyInstagramProfile != "" {
					body["instagram_profile"] = bodyInstagramProfile
				}
				if bodyLinkedinProfile != "" {
					body["linkedin_profile"] = bodyLinkedinProfile
				}
				if cmd.Flags().Changed("share-of-voice-percentage") {
					body["share_of_voice_percentage"] = bodyShareOfVoicePercentage
				}
				if bodyTiktokProfile != "" {
					body["tiktok_profile"] = bodyTiktokProfile
				}
				if bodyXHandle != "" {
					body["x_handle"] = bodyXHandle
				}
			}
			data, statusCode, err := c.PostWithParams(path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "domain", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "domain", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "domain", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "domain", partialFailure.Message))
					}
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "domain",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "domain", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "domain", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyDefaultSearchsettingsNames, "default-searchsettings-names", "", "List of search settings that will be default for keywords on this domain.")
	cmd.Flags().StringVar(&bodyDisplayName, "display-name", "", "<strong>Optional.</strong> If set this will display instead of the domain name. Automatically set for YouTube videos...")
	cmd.Flags().StringVar(&bodyDomain, "domain", "", "No http:// or www. You can enter a path that must be found. Eg. example.com/path. Search result must then begin with...")
	cmd.Flags().BoolVar(&bodyExactMatch, "exact-match", false, "Only include results where the URL found is an exact match to what is entered in domain name")
	cmd.Flags().StringVar(&bodyFacebookProfile, "facebook-profile", "", "Enable ranking of your Facebook profile.")
	cmd.Flags().StringVar(&bodyGoogleBusinessNameList, "google-business-name-list", "", "For some local results Google does not include a link to the website. To make sure we can still find the domain on...")
	cmd.Flags().IntVar(&bodyGroupId, "group-id", 0, "Id of the group the domain should belong to.")
	cmd.Flags().BoolVar(&bodyIncludeSubdomains, "include-subdomains", true, "Include results from sub.domain.com.")
	cmd.Flags().StringVar(&bodyInstagramProfile, "instagram-profile", "", "Enable ranking of your Instagram profile.")
	cmd.Flags().StringVar(&bodyLinkedinProfile, "linkedin-profile", "", "Enable ranking of your LinkedIn profile.")
	cmd.Flags().BoolVar(&bodyShareOfVoicePercentage, "share-of-voice-percentage", false, "Show Share of Voice in percentage for this domain")
	cmd.Flags().StringVar(&bodyTiktokProfile, "tiktok-profile", "", "Enable ranking of your TikTok profile and videos.")
	cmd.Flags().StringVar(&bodyXHandle, "x-handle", "", "X (Twitter) handle for the domain.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
