// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDomainCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "domain",
		Short:  "List, get, create, update, delete domains. Domain payloads include 24-field DomainHistory time-series when...",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDomainCreateCmd(flags))
	cmd.AddCommand(newDomainDeleteCmd(flags))
	cmd.AddCommand(newDomainUpdateCmd(flags))
	return cmd
}
