// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGroupCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "group",
		Short:  "Write API: groups ('Clients') that contain domains.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGroupCreateCmd(flags))
	cmd.AddCommand(newGroupDeleteCmd(flags))
	cmd.AddCommand(newGroupUpdateCmd(flags))
	return cmd
}
