// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newKeywordUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyDescription string
	var bodyDomainId string
	var bodyEnableAutocorrect string
	var bodyIgnoreFeaturedSnippet string
	var bodyIgnoreInShareOfVoice string
	var bodyIgnoreLocalResults string
	var bodyKeywordIds string
	var bodyStarred string
	var bodyTags string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update",
		Short:       "This endpoint updates settings for the given keywords. Only keywords on domains authorized by the token can be...",
		Example:     "  accuranker-pp-cli keyword update --keyword-ids your-token-here",
		Annotations: map[string]string{"pp:endpoint": "keyword.update", "pp:method": "PUT", "pp:path": "/api/v4/keyword/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("keyword-ids") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "keyword-ids")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v4/keyword/"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyDomainId != "" {
					body["domain_id"] = bodyDomainId
				}
				if bodyEnableAutocorrect != "" {
					body["enable_autocorrect"] = bodyEnableAutocorrect
				}
				if bodyIgnoreFeaturedSnippet != "" {
					body["ignore_featured_snippet"] = bodyIgnoreFeaturedSnippet
				}
				if bodyIgnoreInShareOfVoice != "" {
					body["ignore_in_share_of_voice"] = bodyIgnoreInShareOfVoice
				}
				if bodyIgnoreLocalResults != "" {
					body["ignore_local_results"] = bodyIgnoreLocalResults
				}
				if bodyKeywordIds != "" {
					body["keyword_ids"] = bodyKeywordIds
				}
				if bodyStarred != "" {
					body["starred"] = bodyStarred
				}
				if bodyTags != "" {
					body["tags"] = bodyTags
				}
			}
			data, statusCode, err := c.PutWithParams(path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "keyword", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "keyword", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "keyword", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "keyword", partialFailure.Message))
					}
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "keyword",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "keyword", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "keyword", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Description of the keyword")
	cmd.Flags().StringVar(&bodyDomainId, "domain-id", "", "Id of the domain you want to move the keywords to")
	cmd.Flags().StringVar(&bodyEnableAutocorrect, "enable-autocorrect", "", "Enable autocorrect for searches on this keyword")
	cmd.Flags().StringVar(&bodyIgnoreFeaturedSnippet, "ignore-featured-snippet", "", "Whether or not ranking on this keyword will ignore featured snippets.")
	cmd.Flags().StringVar(&bodyIgnoreInShareOfVoice, "ignore-in-share-of-voice", "", "Whether or not this keyword should be ignored in aggregated share of voice")
	cmd.Flags().StringVar(&bodyIgnoreLocalResults, "ignore-local-results", "", "Whether or not ranking on this keyword will ignore local results.")
	cmd.Flags().StringVar(&bodyKeywordIds, "keyword-ids", "", "List of keyword to update")
	cmd.Flags().StringVar(&bodyStarred, "starred", "", "Mark the keyword as starred")
	cmd.Flags().StringVar(&bodyTags, "tags", "", "List of tags for the keyword. Used for filtering or grouping. Updating tags will overwrite existing tags on the keyword.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
