// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newKeywordCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyDescription string
	var bodyDomainId int
	var bodyEnableAutocorrect bool
	var bodyIgnoreFeaturedSnippet bool
	var bodyIgnoreInShareOfVoice bool
	var bodyIgnoreLocalResults bool
	var bodyKeywords string
	var bodySearchsettings string
	var bodyStarred bool
	var bodyTags string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "With this endpoint, you can create one or more keywords on a domain. Keywords can only be created on domains...",
		Example:     "  accuranker-pp-cli keyword create",
		Annotations: map[string]string{"pp:endpoint": "keyword.create", "pp:method": "POST", "pp:path": "/api/v4/keyword/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("domain-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "domain-id")
				}
				if !cmd.Flags().Changed("keywords") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "keywords")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v4/keyword/"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyDomainId != 0 {
					body["domain_id"] = bodyDomainId
				}
				if cmd.Flags().Changed("enable-autocorrect") {
					body["enable_autocorrect"] = bodyEnableAutocorrect
				}
				if cmd.Flags().Changed("ignore-featured-snippet") {
					body["ignore_featured_snippet"] = bodyIgnoreFeaturedSnippet
				}
				if cmd.Flags().Changed("ignore-in-share-of-voice") {
					body["ignore_in_share_of_voice"] = bodyIgnoreInShareOfVoice
				}
				if cmd.Flags().Changed("ignore-local-results") {
					body["ignore_local_results"] = bodyIgnoreLocalResults
				}
				if bodyKeywords != "" {
					var parsedKeywords any
					if err := json.Unmarshal([]byte(bodyKeywords), &parsedKeywords); err != nil {
						return fmt.Errorf("parsing --keywords JSON: %w", err)
					}
					body["keywords"] = parsedKeywords
				}
				if bodySearchsettings != "" {
					var parsedSearchsettings any
					if err := json.Unmarshal([]byte(bodySearchsettings), &parsedSearchsettings); err != nil {
						return fmt.Errorf("parsing --searchsettings JSON: %w", err)
					}
					body["searchsettings"] = parsedSearchsettings
				}
				if cmd.Flags().Changed("starred") {
					body["starred"] = bodyStarred
				}
				if bodyTags != "" {
					var parsedTags any
					if err := json.Unmarshal([]byte(bodyTags), &parsedTags); err != nil {
						return fmt.Errorf("parsing --tags JSON: %w", err)
					}
					body["tags"] = parsedTags
				}
			}
			data, statusCode, err := c.PostWithParams(path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "keyword", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "keyword", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "keyword", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "keyword", partialFailure.Message))
					}
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "keyword",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "keyword", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "keyword", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Description of the keyword")
	cmd.Flags().IntVar(&bodyDomainId, "domain-id", 0, "Id of the domain you want to add the keywords to")
	cmd.Flags().BoolVar(&bodyEnableAutocorrect, "enable-autocorrect", false, "Enable autocorrect for searches on this keyword")
	cmd.Flags().BoolVar(&bodyIgnoreFeaturedSnippet, "ignore-featured-snippet", false, "Whether or not ranking on this keyword will ignore featured snippets.")
	cmd.Flags().BoolVar(&bodyIgnoreInShareOfVoice, "ignore-in-share-of-voice", false, "Whether or not this keyword should be ignored in aggregated share of voice")
	cmd.Flags().BoolVar(&bodyIgnoreLocalResults, "ignore-local-results", false, "Whether or not ranking on this keyword will ignore local results.")
	cmd.Flags().StringVar(&bodyKeywords, "keywords", "", "List of keyword to add to the domain")
	cmd.Flags().StringVar(&bodySearchsettings, "searchsettings", "[]", "List of search settings to use on this keyword")
	cmd.Flags().BoolVar(&bodyStarred, "starred", false, "Mark the keyword as starred")
	cmd.Flags().StringVar(&bodyTags, "tags", "[]", "List of tags for the keyword. Used for filtering or grouping")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
