// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOverviewCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "overview",
		Short:  "High-level account overview. Requires additional plan tier.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOverviewGetGroupAndDomainsCmd(flags))
	cmd.AddCommand(newOverviewGetKeywordForDomainCmd(flags))
	return cmd
}
