// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPromptCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "prompt",
		Short:  "AccuLLM prompts. Requires LLM API plan tier.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPromptCreateCmd(flags))
	cmd.AddCommand(newPromptDeleteCmd(flags))
	cmd.AddCommand(newPromptUpdateCmd(flags))
	return cmd
}
