// Copyright 2026 lasse-jellum. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package store

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	_ "modernc.org/sqlite"
)

// TestStoreWrite_NoSQLITE_BUSY_HighConcurrency exercises the writeMu serialization
// guarantee: 16 fetcher-style goroutines hammer the store with a mix of
// UpsertBatch, SaveSyncState, and SaveSyncCursor calls. Before the mutex
// fix, this test reproduces SQLITE_BUSY at default sync concurrency on
// pure-Go SQLite (modernc.org/sqlite + WAL) because multiple writers
// race for the WAL lock and busy_timeout retries are not exhaustive.
//
// Run under `go test -race` to catch any data races on Store fields.
func TestStoreWrite_NoSQLITE_BUSY_HighConcurrency(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	const goroutines = 16
	const itemsPerBatch = 5

	var wg sync.WaitGroup
	errCh := make(chan error, goroutines*3)

	for g := 0; g < goroutines; g++ {
		wg.Add(1)
		go func(gid int) {
			defer wg.Done()
			rt := fmt.Sprintf("rt_%d", gid)
			items := make([]json.RawMessage, 0, itemsPerBatch)
			for i := 0; i < itemsPerBatch; i++ {
				items = append(items, json.RawMessage(fmt.Sprintf(`{"id": "g%d-i%d"}`, gid, i)))
			}
			if _, _, err := s.UpsertBatch(rt, items); err != nil {
				errCh <- fmt.Errorf("UpsertBatch goroutine %d: %w", gid, err)
				return
			}
			if err := s.SaveSyncState(rt, fmt.Sprintf("cursor-%d", gid), itemsPerBatch); err != nil {
				errCh <- fmt.Errorf("SaveSyncState goroutine %d: %w", gid, err)
				return
			}
			if err := s.SaveSyncCursor(rt, fmt.Sprintf("cursor2-%d", gid)); err != nil {
				errCh <- fmt.Errorf("SaveSyncCursor goroutine %d: %w", gid, err)
				return
			}
		}(g)
	}
	wg.Wait()
	close(errCh)

	for err := range errCh {
		if err == nil {
			continue
		}
		// SQLITE_BUSY surfaces as "database is locked" or "SQLITE_BUSY"
		// in the error message — assert neither occurs.
		msg := err.Error()
		if strings.Contains(msg, "SQLITE_BUSY") || strings.Contains(strings.ToLower(msg), "database is locked") {
			t.Fatalf("got SQLITE_BUSY-class error under concurrent writers: %v", err)
		}
		t.Fatalf("unexpected error under concurrent writers: %v", err)
	}

	// Verify all rows persisted: goroutines * itemsPerBatch in the generic
	// resources table.
	db := s.DB()
	var total int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources`).Scan(&total); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if total != goroutines*itemsPerBatch {
		t.Fatalf("resources total = %d, want %d", total, goroutines*itemsPerBatch)
	}
}

// TestStoreWrite_PanicReleasesLock confirms that a panic inside a locked
// section unwinds via defer s.writeMu.Unlock() so subsequent writers can
// proceed. A leaked lock would deadlock the second call indefinitely.
func TestStoreWrite_PanicReleasesLock(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Trigger panic by passing a nil *Store method receiver indirectly:
	// we call UpsertBatch with malformed JSON that survives Unmarshal
	// (it's wrapped in skipped-count handling) — there's no easy panic
	// path inside a locked section that doesn't also corrupt state, so
	// we instead simulate the post-panic state by manually locking and
	// unlocking, then assert subsequent calls succeed.
	func() {
		defer func() {
			recover()
		}()
		s.writeMu.Lock()
		defer s.writeMu.Unlock()
		panic("simulated writer panic")
	}()

	// Subsequent writer must not block.
	done := make(chan struct{})
	go func() {
		if _, _, err := s.UpsertBatch("post_panic", []json.RawMessage{json.RawMessage(`{"id": "x"}`)}); err != nil {
			t.Errorf("post-panic UpsertBatch: %v", err)
		}
		close(done)
	}()
	<-done
}

// TestUpsertBatch_TemplatedIDFieldOverrideWins exercises the
// per-resource ID-field override. When the spec author annotates a
// path-item with x-resource-id, the profiler emits SyncableResource.IDField,
// the generator templates this into resourceIDFieldOverrides, and
// UpsertBatch consults that map first. This test seeds the override map
// at runtime (since the generated table here may or may not declare any
// override) to assert the lookup path itself works.
func TestUpsertBatch_TemplatedIDFieldOverrideWins(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Inject a runtime override for a synthetic resource. Item carries
	// no generic-fallback field (no id/name/uuid/...) — only a custom
	// "ticker" field. Without the override, all 3 items would be
	// dropped as PK-unresolved; with it, all 3 land.
	prev, hadPrev := resourceIDFieldOverrides["overrideTest"]
	resourceIDFieldOverrides["overrideTest"] = "ticker"
	defer func() {
		if hadPrev {
			resourceIDFieldOverrides["overrideTest"] = prev
		} else {
			delete(resourceIDFieldOverrides, "overrideTest")
		}
	}()

	items := []json.RawMessage{
		json.RawMessage(`{"ticker": "AAPL", "price": 100}`),
		json.RawMessage(`{"ticker": "GOOG", "price": 200}`),
		json.RawMessage(`{"ticker": "MSFT", "price": 300}`),
	}
	stored, extractFailures, err := s.UpsertBatch("overrideTest", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != 3 {
		t.Fatalf("stored = %d, want 3 (templated override should resolve all PKs)", stored)
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}
}

// TestUpsertBatch_GenericFallbackList covers each name in the reduced
// fallback list. The kalshi-accreted names (ticker/event_ticker/series_ticker)
// were dropped because the user owns kalshi and will regenerate
// it with x-resource-id annotations; this test pins what the generic list
// is now responsible for so a future trim doesn't silently break unannotated
// specs.
func TestUpsertBatch_GenericFallbackList(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	for _, key := range []string{"id", "ID", "gid", "sid", "uid", "uuid", "guid", "name", "slug", "key", "code"} {
		t.Run(key, func(t *testing.T) {
			rt := "fallback_" + key
			items := []json.RawMessage{
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "value-1")),
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "value-2")),
			}
			stored, extractFailures, err := s.UpsertBatch(rt, items)
			if err != nil {
				t.Fatalf("UpsertBatch(%q): %v", key, err)
			}
			if stored != 2 {
				t.Fatalf("stored = %d, want 2 (fallback %q must resolve)", stored, key)
			}
			if extractFailures != 0 {
				t.Fatalf("extractFailures = %d, want 0", extractFailures)
			}
		})
	}

	// Negative: API-specific names dropped must NOT resolve.
	// Spec authors annotate these via x-resource-id instead.
	for _, key := range []string{"ticker", "event_ticker", "series_ticker"} {
		t.Run("dropped_"+key, func(t *testing.T) {
			rt := "dropped_" + key
			items := []json.RawMessage{
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "v1")),
			}
			stored, extractFailures, err := s.UpsertBatch(rt, items)
			if err != nil {
				t.Fatalf("UpsertBatch(%q): %v", key, err)
			}
			if stored != 0 {
				t.Fatalf("stored = %d, want 0 (%q must NOT be in the generic fallback list)", stored, key)
			}
			if extractFailures != 1 {
				t.Fatalf("extractFailures = %d, want 1 (%q drop must surface as extract failure)", extractFailures, key)
			}
		})
	}
}

// TestUpsertBatch_ExtractFailuresReturnedForPerItemMisses pins the third
// return value: items that survive JSON unmarshal but have no extractable
// PK (templated override AND generic fallback both miss) bump
// extractFailures. The sync.go.tmpl call site uses this to emit the
// per-resource primary_key_unresolved sync_anomaly the first time silent
// drops occur.
func TestUpsertBatch_ExtractFailuresReturnedForPerItemMisses(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "ok-1"}`),
		json.RawMessage(`{"some_random_field": "no-pk-here"}`),
		json.RawMessage(`{"id": "ok-2"}`),
		json.RawMessage(`{"another_field": 42}`),
	}
	stored, extractFailures, err := s.UpsertBatch("mixed_extraction", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != 2 {
		t.Fatalf("stored = %d, want 2 (only items with id should land)", stored)
	}
	if extractFailures != 2 {
		t.Fatalf("extractFailures = %d, want 2 (two items have no extractable PK)", extractFailures)
	}
}

// TestUpsertBatch_PopulatesAccountsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed accounts table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesAccountsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("accounts", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "accounts").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "accounts")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count accounts: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("accounts count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesBrandTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed brand table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesBrandTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("brand", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "brand").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "brand")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count brand: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("brand count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesPromptsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed prompts table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesPromptsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "brands_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "brands_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "brands_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("prompts", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "prompts").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "prompts")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count prompts: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("prompts count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandPromptsGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandPromptsGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "brands_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("prompts", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "prompts").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "prompts")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count prompts: %v", err)
	}
	if typed != 0 {
		t.Fatalf("prompts count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "brands_id")
	}
}

// TestUpsertBatch_SetsPromptsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsPromptsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("prompts", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "prompts")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesDomainTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed domain table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesDomainTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("domain", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "domain").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "domain")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count domain: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("domain count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesDomainsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed domains table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesDomainsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("domains", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "domains").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "domains")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count domains: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("domains count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesKeywordsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed keywords table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesKeywordsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "domains_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "domains_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "domains_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("keywords", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "keywords").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "keywords")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count keywords: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("keywords count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandKeywordsGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandKeywordsGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "domains_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("keywords", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "keywords").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "keywords")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count keywords: %v", err)
	}
	if typed != 0 {
		t.Fatalf("keywords count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "domains_id")
	}
}

// TestUpsertBatch_SetsKeywordsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsKeywordsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("keywords", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "keywords")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesLandingPagesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed landing_pages table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesLandingPagesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "domains_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "domains_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "domains_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("landing_pages", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "landing_pages").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "landing_pages")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count landing_pages: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("landing_pages count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandLandingPagesGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandLandingPagesGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "domains_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("landing_pages", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "landing_pages").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "landing_pages")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count landing_pages: %v", err)
	}
	if typed != 0 {
		t.Fatalf("landing_pages count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "domains_id")
	}
}

// TestUpsertBatch_SetsLandingPagesParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsLandingPagesParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("landing_pages", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "landing_pages")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesTagsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed tags table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTagsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "domains_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "domains_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "domains_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("tags", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "tags").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "tags")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count tags: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("tags count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandTagsGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandTagsGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "domains_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("tags", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "tags").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "tags")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count tags: %v", err)
	}
	if typed != 0 {
		t.Fatalf("tags count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "domains_id")
	}
}

// TestUpsertBatch_SetsTagsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsTagsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("tags", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "tags")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesGroupTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed group table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesGroupTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("group", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "group").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "group")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count group: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("group count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesKeywordTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed keyword table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesKeywordTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("keyword", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "keyword").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "keyword")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count keyword: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("keyword count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesOverviewTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed overview table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesOverviewTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("overview", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "overview").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "overview")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count overview: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("overview count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesPromptTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed prompt table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesPromptTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("prompt", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "prompt").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "prompt")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count prompt: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("prompt count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesStatusTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed status table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesStatusTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("status", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "status").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "status")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count status: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("status count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}
